### ISSUE TITLE
error loading data

### ISSUE THREAD

**Issue by fab679** [adam-cowley/twitch-project#1]
When loading the data i recieve this error
Cannot merge node using null property value for id (Failure when processing file '/home/fabisch/.config/Neo4j%20Desktop/Application/neo4jDatabases/database-34a9a402-b174-400c-9983-b9ed7d4852ec/installation-4.1.0/import/movies_metadata.csv' on line 19732.)

**Comment by adam-cowley** [comment]
Yeah I had this problem too, that movies metadata file has a few line breaks in the overviews that break the LOAD CSV query.  If you search for Shark Avalanche then you'll see what I mean.  I ended up removing the line breaks, I think there were 4 or 5 in the end that needed fixing.  

[Try this file instead](https://neo4j-datasets-public.s3-us-west-2.amazonaws.com/neoflix/movies_metadata.csv) or you can run the following cypher query to find the rows with the line breaks:
```
LOAD CSV WITH HEADERS FROM 'file:///movies_metadata.csv' AS row
WITH row WHERE row.id = ''
RETURN row.adult
```
