### ISSUE TITLE
 Nest can't resolve dependencies of the NEO4J_CONFIG (?). Please make sure that the argument NEO4J_C ONFIG at index [0] is available in the Neo4jModule context

### ISSUE THREAD

**Issue by BenMstfa** [adam-cowley/twitch-project#4]
Thanks so much for your weekly episodes as they are insightful for me. 

I have a problem to get things to work as I have followed your steps but I think missed something causing that error  

```
[Nest] 3564   - 08/08/2020, 3:27:51 PM   [ExceptionHandler] Nest can't resolve dependencies of the NEO4J_CONFIG (?). Please make sure that the argument NEO4J_C
ONFIG at index [0] is available in the Neo4jModule context.

Potential solutions:
- If NEO4J_CONFIG is a provider, is it part of the current Neo4jModule?
- If NEO4J_CONFIG is exported from a separate @Module, is that module imported within Neo4jModule?
  @Module({
    imports: [ /* the Module containing NEO4J_CONFIG */ ]
  })
 +72ms
```

I'll appreciate it if you could take a look into my code [here](https://github.com/BenMstfa/learning-nest) and tell me what's wrong with it. 

BR

**Comment by adam-cowley** [comment]
It looks like you've copied down a line in `neo4j-constants.ts` and not changed it so the dependency injection is getting confused.   I updated the NEO4J_DRIVER line and everything seems to work

```
export const NEO4J_CONFIG = 'NEO4J_CONFIG';
export const NEO4J_DRIVER = 'NEO4J_DRIVER' // not: 'NEO4J_CONFIG';
```

I also spotted that you've set the neo4j port to `7686` rather than the default `7687` - if you haven't changed the port and get neo4j connection errors then that will be why.

**Comment by BenMstfa** [comment]
Thanks so much for your investigation and fix, I really appreciate that.

I'll fix both issues to follow up with the rest of the episodes. 

Best Regards Sir.

**Comment by craigmrock** [comment]
Hi, getting "no router services available" error. could you please take a look and see if you can resolve this? I have done some searching, but no luck so far. [https://github.com/craigmrock/neo4j-nestjs/tree/master](url)

**Comment by adam-cowley** [comment]
That error usually means that the host or port used to connect to Neo4j is incorrect.  I'd double-check those are correct, the server is running and that you can get to the browser on port 7474 for that server (eg. http://localhost:7474)

**Comment by craigmrock** [comment]
Thanks Adam, I am trying to connect to neo4j aura database, so I had to change the schema also to neo4j+s on the app.module too. Thanks again for a great learning experience!
